Added parameter support to update-facls

diff --git a/files/update-facls b/files/update-facls
--- a/files/update-facls
+++ b/files/update-facls
@@ -6,24 +6,26 @@
 # Sets correct file permissions for shared web projects.
 #
 # Create /etc/update-facls.conf with dir, user and group, e.g.:
-# /srv/www/monheim.de/www-dev/htdocs     www-dev        monheim
+# /srv/www/monheim.de/www-dev/htdocs www-dev monheim
 #
-# v2018-04-13-1, markus.meissner@meissner.IT
+# Calling without parameters processes all configured directories.
+# Calling with parameter "dir" processes only the specified directory (which 
+# still must be set in /etc/update-facls.conf).
+#
+# v2020-04-08-1, markus.meissner@meissner.IT
 
 # exit on error (equals set -o errexit)
 set -e
-# exit if variable is unset
-set -u
 
 # No config file no work to do
 [ -f /etc/update-facls.conf ] || exit 0
 
-while read -r line; do
-    IFS=' ' read -r -a array <<< "$line"
-    DIR=${array[0]}
-    OWNER=${array[1]}
-    GROUP=${array[2]}
-
+function updateFacls {
+    # exit if variable is unset
+    set -u
+    DIR=$1
+    OWNER=$2
+    GROUP=$3
     cd ${DIR}
     chown -R ${OWNER}:${GROUP} ${DIR}
     chmod -R o-w ${DIR}
@@ -33,6 +35,21 @@ while read -r line; do
             -exec chmod g+rwx {} \; \
             -exec setfacl -m g:${GROUP}:rwx {} \; \
             -exec setfacl -d -m g:${GROUP}:rwx {} \;
+}
 
-done < /etc/update-facls.conf
+if [ -z "$1" ]; then
+    while read -r line; do
+        IFS=' ' read -a array <<< "$line"
+        updateFacls ${array[0]} ${array[1]} ${array[2]}
+    done < /etc/update-facls.conf
+else
+    line=$(egrep "^$1" /etc/update-facls.conf | head -n1)
+    if [ -z "${line}" ]; then
+        echo "Could not read '$1' from /etc/update-facls.conf"
+        exit 1
+    fi
+    IFS=' ' read -a array <<< "$line"
+    echo "Processing '${array[0]}' with user '${array[1]}' and group '${array[2]}'"
+    updateFacls ${array[0]} ${array[1]} ${array[2]}
+fi
 
